# Generated by Django 4.0 on 2022-11-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board2", "0004_remove_post_content_post_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="file_upload",
        ),
    ]
