# Generated by Django 4.0 on 2022-10-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_address1_alter_user_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
