# Generated by Django 4.0 on 2022-10-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_zipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="zipcode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
