# Generated by Django 4.0 on 2022-10-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board1", "0006_category_post_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="subject",
        ),
    ]
